
<?php

/**
 * Apadrinado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tiendaonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Apadrinado extends BaseApadrinado {

    /**
     * Creat registro padrino - apadrinado
     * @param type $padrino
     * @param Apadrinado $apadrinado 
     */
    public static function crearUsuarioApdrinado($padrino, $apadrinado) {

        $a = new Apadrinado();
        $a->setUsuarioId($padrino);
        $a->setEmailApadrinado($apadrinado);
        $a->setEstado(1);
        $a->save();
    }

}