<?php

/**
 * ApadrinadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApadrinadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApadrinadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Apadrinado');
    }
}