<?php

/**
 * DireccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DireccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DireccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Direccion');
    }
}