<?php

/**
 * Estado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tiendaonline
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Estado extends BaseEstado
{
}
