<?php

/**
 * EstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estado');
    }
}