<?php

/**
 * MarcaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarcaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarcaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Marca');
    }
}