<?php

/**
 * MenuMarcasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuMarcasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuMarcasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MenuMarcas');
    }
}