<?php

/**
 * SubcategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubcategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubcategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subcategoria');
    }
}